name: adibasa_app
description: "aplikasi belajar Bahasa jawa, dengan metode gamifikasi, latihan interaktif, dan pembelajaran bertahap."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  get: ^4.3.8
  audioplayers: ^5.2.1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logoadi.png
    - assets/images/icon.png
    - assets/images/badak_berpendidikan_tinggi.png
    - assets/images/badak_dapet_bintang.png
    - assets/images/badak_ngegame.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
    - assets/images/
    - assets/
    - data/kamus_jawa_indonesia.json
    - assets/dummy/greetings_lessons.json
    - assets/star/
    - assets/audio/success.mp3
    - assets/audio/failure.mp3

