name: adibasa_app
description: "aplikasi belajar Bahasa jawa, dengan metode gamifikasi, latihan interaktif, dan pembelajaran bertahap."
publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  get: ^4.3.8
  audioplayers: ^5.2.1
  flutter_riverpod: ^2.6.1
  popover: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  change_app_package_name: ^1.4.0


flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/
    - assets/star/
    - data/kamus_jawa_indonesia.json
    - assets/images/peta_bagian_1.jpg
    - assets/images/peta_bagian_2.jpg
    - assets/images/peta_bagian_3.jpg
    - assets/images/lock.png


flutter_launcher_icons:
  android: true
  image_path: "assets/images/launcher_icon.png"
  adaptive_icon_foreground: "assets/images/launcher_icon.png"
  adaptive_icon_background: "#F1DFBE"
  adaptive_icon_foreground_inset: 20