name: adibasa_app
description: "aplikasi belajar Bahasa jawa, dengan metode gamifikasi, latihan interaktif, dan pembelajaran bertahap."
publish_to: "none"

version: 2.0.0+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  get: ^4.3.8
  audioplayers: ^5.2.1
  flutter_riverpod: ^2.6.1
  popover: ^0.3.1
  confetti: ^0.7.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/
    - assets/star/
    - data/kamus_jawa_indo.json

