name: adibasa_app
description: "aplikasi belajar Bahasa jawa, dengan metode gamifikasi, latihan interaktif, dan pembelajaran bertahap."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  get: ^4.3.8
  audioplayers: ^5.2.1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - data/kamus_jawa_indonesia.json
    - assets/dummy/greetings_lessons.json
    - assets/star/
    - assets/audio/success.mp3
    - assets/audio/failure.mp3
